---
title: "decision_tree"
author: "Ojas Kishore Shirekar"
date: "3/7/2017"
output: html_document
---

```{r setup, include=FALSE}
library(rpart)
library(rpart.plot)
library(ggplot2)
library(RColorBrewer)
```

```{r}
bankTrain <- read.table("../data/bank-sample.csv", header = TRUE, sep = ",")
# Drop a few columns
drops = c("age", "balance", "day", "campaign", "pdays", "previous", "month")
bankTrain <- bankTrain[, !(names(bankTrain)) %in% drops]
summary(bankTrain)
dim(bankTrain)
```

```{r}
fit <- rpart(subscribed ~ job + marital + education + default +
               housing + loan + contact + poutcome,
             method = "class",
             data = bankTrain,
             control = rpart.control(minsplit = 1),
             parms = list(split = "information"))
summary(fit)
```

```{r}
rpart.plot(fit, type = 4,
           extra = 2,
           clip.right.labs = FALSE,
           varlen = 0,
           faclen = 3)
```
```{r}
pred <- predict(fit, bankTrain, type = "class")
library(caret)
confusionMatrix(pred, bankTrain$subscribed)
```

```{r}
set.seed(4)
x <- rnorm(10)
y <- rnorm(10)
z <- rep(c(0, 1), c(5, 5))
dt = data.frame(x=x, y=y, z=z)
qplot(x, y, col= as.factor(dt$z))

E <- -0.5 * log2(0.5) - (1 - 0.5) * log2(1 - 0.5)
E # impurity of a Highly impure attr

z <- sample(c(0, 1), 10 , replace = T, prob = c(0.2, 0.6))
dt <- data.frame(x=x, y=y, z=z)
qplot(x,y,col=as.factor(dt$z))
```

```{r}
x <- sort(runif(1000))
head(x)

y <- data.frame(x=x, y=-x * log2(x) - (1 - x) * log2(1 - x))
plot(y, type = "l",  xlab = "P(X=1)", ylab = expression("H"["X"])) + grid()
```