---
title: "Naive Bayes Classifier"
author: "Ojas Kishore Shirekar"
date: "2/28/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(klaR)
library(ggplot2)
```

## Splitting data set in 80-20 train-test
```{r data_split}
set.seed(42)
data("iris")
trainIndex <- createDataPartition(iris$Species, p=0.8, list = FALSE)
data_train <- iris[trainIndex, ]
data_test <- iris[-trainIndex, ]
```

```{r}
summary(iris)
```

```{r}
str(iris)
```


## Plotting sepal length vs sepal width
```{r plot_sLen_sWid}
qplot(iris$Sepal.Length, iris$Sepal.Width, color=iris$Species)
```



## Plotting petal length and petal width
```{r plot_pLen_pWid}
qplot(iris$Petal.Length, iris$Petal.Width, color=iris$Species)
```



## Building the model

```{r}
NB.model <- NaiveBayes(Species~., data=data_train)
summary(NB.model)
```


## Accuracy on the training set.
```{r}
train.predict <- predict(NB.model, data_train)
confusionMatrix(train.predict$class, data_train$Species)
```

## Accuracy of predictions on the testing set.
```{r}
x_test <- data_test[,1:4]
y_test <- data_test[, 5]
test.predict <- predict(NB.model, x_test)
confusionMatrix(test.predict$class, y_test)
```


```{r}
# Predict the classes for the new data set (SL=5.4, SW=4.7, PPL=6.8, PW=9.1)
new.flower<-data.frame(Sepal.Length=5.4, Sepal.Width=4.7, Petal.Length=6.8, Petal.Width=9.1)
new_pred <- predict(NB.model, newdata=new.flower)
new_pred
```


## Just a simple something
```{r}
x = rnorm(200)
y = rnorm(200, 2, 3)
z <- data.frame(Math_Marks=x, Stat_Marks=y, Grades=as.factor(sample(c("a", "b", "c", "d", "e"), 200, replace=T)))
head(z)
```

```{r}
set.seed(42)
trainIndex <- createDataPartition(z$Grades, p=0.8, list=FALSE)
z.train = z[trainIndex, ]
z.test = z[-trainIndex, ]
```

```{r}
z.model <- NaiveBayes(Grades~., data=z.train)
summary(z.model)
```

```{r}
x_test = z.test[,1:2]
y_test = z.test[, 3]

z.predict <- predict(z.model, x_test)
confusionMatrix(z.predict$class, y_test)
```
