---
title: "first_exp"
output: html_document
---

## My First Document
```{r}
library(ggplot2)
x <- rnorm(100)
y <- rnorm(100)
z <- sample(c("M", "F"), 100, replace = TRUE)
dt <- data.frame(x, y, z)
head(dt)
summary(dt)
qplot(x, y, xlab = 'x', ylab = 'y', main = '100 Random Numbers', color=as.factor(z))
plot(x, y, xlab = 'x', ylab = 'y', main = '100 Random Numbers', col=as.factor(z), pch=4)
legend('topright', c("M", "F") , pch=4, col=c('red', 'black'), bty='n', cex=.75)
```

## Plot histogram
```{r}
# using normal stuff

par(mfrow=c(1, 2))
hist(x, main = '100 Random numbers', col = 'blue')
rug(x)
abline(v = median(x), col='red', lwd=2)
hist(y)
qplot(x, main = '100 Random Numbers', geom = "histogram", bins=30)
```

## Bar Plot
```{r}
tab <- table(z)
tab
barplot(tab)

qplot(z, geom = 'bar')

heatmap(table(x ,y))
```

## Iris data set heatmap and barplot
```{r}
# interpret this heatmap
par(xpd=NA)
heatmap(as.matrix(iris[, -5]))
qplot(iris$Species, geom = 'bar')
```

## Box plots

```{r}
ggplot(dt, aes(x=x, y=y)) + geom_boxplot()
boxplot(x, col = 'cyan')
```